data:extend({
    {
        type = "string-setting",
        name = "prefix",
        setting_type = "runtime-per-user",
        default_value = "mapshot/",
        localised_name = "Prefix",
        localised_description = "Prefix to add to all generated filenames.",
        order = "000",
    },
    {
        type = "int-setting",
        name = "tilemin",
        setting_type = "runtime-per-user",
        default_value = 256,
        allowed_values = {16, 32, 64, 128, 256, 512, 1024, 2048, 4096},
        localised_name = "Smallest tile size",
        localised_description = "Size in in-game units of a tile for the most zoomed layer.",
        order = "100",
    },
    {
        type = "int-setting",
        name = "tilemax",
        setting_type = "runtime-per-user",
        default_value = 1024,
        allowed_values = {16, 32, 64, 128, 256, 512, 1024, 2048, 4096},
        localised_name = "Largest tile size",
        localised_description = "Size in in-game units of a tile for the least zoomed layer.",
        order = "101",
    },
    {
        type = "int-setting",
        name = "resolution",
        setting_type = "runtime-per-user",
        default_value = 1024,
        minimum_value = 16,
        maximum_value = 16384,
        localised_name = "Tile Resolution",
        localised_description = "Pixel size for generated tiles.",
        order = "200",
    },
    {
        type = "int-setting",
        name = "jpgquality",
        setting_type = "runtime-per-user",
        default_value = 75,
        minimum_value = 1,
        maximum_value = 100,
        localised_name = "JPG quality",
        localised_description = "Compression quality for jpg files.",
        order = "201",
    },

    -- following settings are largely internal, for driving
    -- from CLI.
    {
        type = "bool-setting",
        name = "onstartup",
        setting_type = "runtime-per-user",
        default_value = false,
        localised_name = "Trigger on start",
        localised_description = "Automatically generate a shot on startup.",
        hidden = true,
        order = "301",
    },
    {
        type = "string-setting",
        name = "shotname",
        setting_type = "runtime-per-user",
        default_value = "",
        allow_blank = true,
        localised_name = "Shot name",
        localised_description = "Name of the mapshot to create.",
        hidden = true,
        order = "302",
    },
})